### ISSUE TITLE
I need this so much!...

### ISSUE THREAD

**Issue by RefsyMcArf** [FabioZumbi12/PixelVip#1]
So there is what i need on my server, i will make Packages out of your plugin for so much things
but i need every package to have his own ''WhenFinishCommand''. Cuz for example when they have 
rank ''Vip'' there is a package that give them Fly.. (essentials.fly) i don't want when the fly package finishes the finish command to be clearing his rank. I will be so grateful. Thanks.

**Comment by FabioZumbi12** [comment]
Add all commands in this option. If the player does not have fly, nothing will happens (as example). One finish command per vip will not be added :/
