### ISSUE TITLE
Vender VIP e desban

### ISSUE THREAD

**Issue by jeanlorencini** [FabioZumbi12/PixelVip#10]
Primeiramente obrigado por disponibilizar este plugin fantástico!
Minha sugestão é que adicione um comando para o player que comprou VIP poder vender por dinheiro do server para outros players, e tambem que possa vender desban ou dar desban em si proprio com a key de vip que adquiriu.

**Comment by FabioZumbi12** [comment]
Dar desban pra si proprio vc teria que criar um jeito de permitir o player se logar por alguns minutos pra ele usar a key, que iria executar o comando de desban, ou vc desbanir offline. O plugin so funciona online no server, mas tem opção de mysql.

Player vender key nao pretendo por.
