### ISSUE TITLE
Não remover do grupo atual e Jogar para outro grupo sem ser o anterior.

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/PixelVip#11]
Basicamente eu gostaria de pedir **2 configurações** que eu não encontrei no plugin.

A primeira é para **não remover** o jogador do grupo atual que ele se encontrá. Já que no meu servidor existem jogadores em mais de 1 grupo. Exemplo: Um jogador novo entra automaticamente como guest (sem grupo) porém se ele for um bom construtor, ele entra para o grupo builder que tem acesso aos comandos de mc e fly se esse jogador comprar um vip, o pixelvip tira ele do grupo builder e quando o vip acaba joga ele de volta pro grupo builder. Porém digamos que no meu vip eu não queira por o comando fly, por ser um vip mais barato. Se o jogador era do grupo builder ele perde o fly após comprar o vip. Isso porque o pixelvip tira ele do grupo que ele estava. Não encontrei na config.yml uma forma de desativar isso sem atrapalhar o restante da configuração que faz ele jogar o jogador no grupo vip do pex e dar reload e quando acabar volta ele pro grupo. (isso esta funcionando normalmente)

Já o segundo pedido, é para que o pixelvip não jogue ele de volta para o grupo que ele estava originalmente, eu gostaria de para cada configuração de grupo de vip existente, houvesse uma opção de definir um grupo específico para cada vip, ou seja. Um ExVip.

Resumindo: 
**1) não remover o jogador do grupo atual**

2) adicionar opção para cada vip ao acabar, 
**o que já existe**
2a) remover do grupo vip em questão e adicionar em um grupo específico.
commandsToRunOnVipFinish:
pex user {p} group remove {vip}
**o que não existe**
2b) adicionar o jogador a um grupo exvip de acordo com o grupo vip que ele estava
**não existe a opção atualmente - essa é uma sugestão para o plugin**

É possível ?

Atualmente as opções do config são genéricas para todos os vips. Gostaria de uma configuração mais personalizada ou seja, adicionar para cada vip diferente e não 1 opção pra todos seria um 

commandsToRunOnVipFinish: 
pex user {p} group remove {vip} seguido de um
pex user {p} group add {exvip1} 

o restante das minhas configs estão assim:
useVault-toChangePlayerGroup: true
cmdToReloadPermPlugin: pex reload

também não entendi esse nome dessa opção: cmdonremovevip:  essa é a opção que adiciona o player no grupo vip mas essa opção também remove o player do grupo atual, teria como separar essa opção ou dar a opção pro dono do servidor que quiser que o jogador não seja removido do grupo atual ?
cmdOnRemoveVip:
pex user {p} group add {vip}

commandsToRunOnChangeVip: []

queueCmdsForOfflinePlayers: false

**Comment by comonier** [comment]
para a segunda opção achei a solução

groups:
  vip:
    commands:
        - pex user {p} group add exvip

**Comment by FabioZumbi12** [comment]
Pra primeira, testa a versão dev lá do discord.

**Comment by comonier** [comment]
aquela solução que eu falei de adicionar o grupo exvips nos comandos q são executados quando ele ativa a key ta deixando o exvip na frente do grupo vip tem como alterar ?

**Comment by FabioZumbi12** [comment]
Enquanto a isso agora tu sabe q eh só arrumar o "peso" no pex, e pra o set/add do vault, remove a config `useVault-toChangePlayerGroup: true` (ainda deve ta na config mas nao funciona mais) e adicionei a nova que vc ja viu.

A nova permite vc usar o vault ou nao (igual a opção antiga ja fazia) mas pode escolher o como de mudança do grupo, se vai `add` ou `set`.
