### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by thtTNT** [FabioZumbi12/PixelVip#12]
I don't know why, I can't run command "givevip". It throws NullPointerException. I will clone your code then fix the bug. I love you plugin much. Fighting! Waiting for my PR!

**Comment by FabioZumbi12** [comment]
You can paste the error here to i try to fix

**Comment by thtTNT** [comment]
There are two bugs. I told you one first, I run in 1.10.2 Sponge server. It throw NullPointerException at [PixelVip.class:212]. I guess the "perms" is null. 

You wrote like this.

if (v.startsWith("5") || v.startsWith("6")){
				this.perms = (PVPermsAPI)Class.forName("br.net.fabiozumbi12.pixelvip.sponge.PVPermsAPI56").newInstance();
			}
if (v.startsWith("7") || v.startsWith("8")){
				this.perms = (PVPermsAPI)Class.forName("br.net.fabiozumbi12.pixelvip.sponge.PVPermsAPI78").newInstance();
}

Do you think it's better to add a default PVPermsAPI when have no matched version?
