### ISSUE TITLE
Delay to Give/Remove VIP

### ISSUE THREAD

**Issue by Golvore** [FabioZumbi12/PixelVip#17]
Hello, I've had this problem for a long time, the plugin takes too long to deliver and remove the vip through vault (like 10 - 40 mins).

**Comment by FabioZumbi12** [comment]
This why you have a config option to reload the permissions plugin. This is not PixelVip delay.

**Comment by Golvore** [comment]
I use LuckPerms, i can't reload the database, it only reloads the config.

**Comment by BrainStone** [comment]
Yes you can (`/lp sync`) and there’s no need whatsoever to either delay when using the Vault API or even reloading the plugin if the permissions properly implements the Vault API.

**Comment by FabioZumbi12** [comment]
Yup. I've noticed vault have a little delay depending of... i dont know why. But using pex, you need to reload the plugin to get the perms set immediately (as example)

**Comment by mcpanglei** [comment]
i have the same problem and i use LuckPerms too

**Comment by LuisGVE** [comment]
Not solved
