### ISSUE TITLE
Internal error occurred (spigot-1.13)

### ISSUE THREAD

**Issue by EduBRz** [FabioZumbi12/PixelVip#18]
10.08 14:36:32 [Server] INFO EduBRs issued server command: /darvip EduBRs vip1 15
10.08 14:36:32 [Server] ERROR null
10.08 14:36:32 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'darvip' in plugin PixelVip v2.0.4
10.08 14:36:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
10.08 14:36:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
10.08 14:36:32 [Server] INFO Caused by: java.lang.NullPointerException
10.08 14:36:32 [Server] INFO at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.activateVip(PVConfig.java:382) ~[?:?]
10.08 14:36:32 [Server] INFO at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.addVip(PVCommands.java:609) ~[?:?]
10.08 14:36:32 [Server] INFO at br.net.fabiozumbi12.pixelvip.bukkit.cmds.PVCommands.onCommand(PVCommands.java:101) ~[?:?]
10.08 14:36:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-417cfb3-0e1d79b]
10.08 14:36:32 [Server] INFO ... 15 more

**Comment by FabioZumbi12** [comment]
Foi arrumado na ultima build: https://host.areaz12server.net.br:8080/job/PixelVip/
