### ISSUE TITLE
Pex reload

### ISSUE THREAD

**Issue by Sousa42333** [FabioZumbi12/PixelVip#25]
Podia liberar para editar o comando de reload de config(como por exemplo meter "nope" para assim nao bugar console com spam de pex reload)
![image](https://user-images.githubusercontent.com/44007831/46701454-9e7b6080-cc17-11e8-9ae5-e50e1369669c.png)

**Comment by Sousa42** [comment]
https://pastebin.com/gSgQnk6G

**Comment by FabioZumbi12** [comment]
Só por qualquer outro comando. Deixar em branco não da né? E tambem esse spam é algum loop devido os players não estarem entrando no grupo vip corretamente!
