### ISSUE TITLE
WARN Task #91 for PixelVip v2.0.4 generated an exception

### ISSUE THREAD

**Issue by cosoc** [FabioZumbi12/PixelVip#28]
WARN Task #91 for PixelVip v2.0.4 generated an exception 18.01 12:15:04 [服务器] 信息 java.lang.NullPointerException: null 18.01 12:15:04 [服务器] 信息 at br.net.fabiozumbi12.pixelvip.bukkit.db.PVDataMysql.getActiveVipList(PVDataMysql.java:387) ~[?:?] 18.01 12:15:04 [服务器] 信息 at br.net.fabiozumbi12.pixelvip.bukkit.PVConfig.getVipList(PVConfig.java:825) ~[?:?] 18.01 12:15:04 [服务器] 信息 at br.net.fabiozumbi12.pixelvip.bukkit.PixelVip.lambda$reloadVipTask$2(PixelVip.java:170) ~[?:?] 18.01 12:15:04 [服务器] 信息 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1596] 18.01 12:15:04 [服务器] 信息 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1596] 18.01 12:15:04 [服务器] 信息 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1596] 18.01 12:15:04 [服务器] 信息 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1596] 18.01 12:15:04 [服务器] 信息 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1596] 18.01 12:15:04 [服务器] 信息 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1596]

**Comment by FabioZumbi12** [comment]
Ok, no more info, no versions, cant help!
