### ISSUE TITLE
WARN Task #94 for PixelVip v2.0.4 generated an exception 1

### ISSUE THREAD

**Issue by cosoc** [FabioZumbi12/PixelVip#29]
WARN Task #94 for PixelVip v2.0.4 generated an exception 19.01 15:34:09 [服务器] 信息 java.lang.RuntimeException: The operation to load user data for '3fe10c80-4c1a-3174-a3f3-615214bd536b' was cancelled by LuckPerms. This is NOT a bug. 19.01 15:34:09 [服务器] 信息 The lookup request was made on the main server thread. It is not safe to execute a request to 19.01 15:34:09 [服务器] 信息 load username data from the database in this context. 19.01 15:34:09 [服务器] 信息 If you are a plugin author, please consider making your request asynchronously. 19.01 15:34:09 [服务器] 信息 Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true

**Comment by FabioZumbi12** [comment]
Ok, no more info, no versions, cant help!
