### ISSUE TITLE
Sugestão 

### ISSUE THREAD

**Issue by galoti** [FabioZumbi12/PixelVip#31]
Olá Fabio, vi que recentemente adicionou algumas APIs de pagamento na versão do Sponge e gostaria de sugerir a opção de pagamento da Paygol. Ela seria mais voltada para players da Europa(como Portugal) que se sentem mais seguros com o PaySafeCard.(Paypal também possui suporte ao PaySafe, mas não em transações envolvendo o Brasil)

**Comment by FabioZumbi12** [comment]
Olá. Com a implementação das apis atuais, ficou facil de adicionar novas apis ao pixelvip, mas eu tava olhando o paygol e não tem muitas informações sobre integração com java, nem nada pronto, somente para integração via página da web. Se tivesse algo em java eu implementaria.
