### ISSUE TITLE
VIP Group

### ISSUE THREAD

**Issue by newbie029** [FabioZumbi12/PixelVip#32]
Can you make option to automatically remove player from vip group if they are not in pixelvip database?
I just migrate from PEX to Luckperm
I also want to migrate from VipZero to PixelVip
but the problem is my players dont have member group, only vip group. I have add them to pixelvip database but when the vip expire they dont removed from the vip group.

**Comment by FabioZumbi12** [comment]
All is controlled via commands setup on config. You can sçdefine via commands if will set or add the plauer groups. Pixelvip have a scheduler to remove players who is not on vips groups, if thos groups is configured on configs.
