### ISSUE TITLE
[BUG] Taks cancelada pelo luckperms.

### ISSUE THREAD

**Issue by juanmuscaria** [FabioZumbi12/PixelVip#33]
**Descreva o bug**
Algumas tasks do PixelVip é cancelada pelo luckperms
```
[Server] WARN [PixelVip] Task #29 for PixelVip v2.0.4 generated an exception
[Server] INFO java.lang.RuntimeException: The operation to load user data for '9e03072f-59c2-3960-9bbe-6736ed47e780' was cancelled by LuckPerms. This is NOT a bug. 
[Server] INFO The lookup request was made on the main server thread. It is not safe to execute a request to 
[Server] INFO load data for offline players from the database in this context. 
[Server] INFO If you are a plugin author, please consider making your request asynchronously. [Server] INFO Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
[Server] INFO in the LP config, but should consider the consequences (lag) before doing so.
```
**Reproduzir**
Etapas para reproduzir o comportamento:
Tenha o luckperms instalado e alguém com vip ativo.

**Comportamento esperado**
Não ter a task cancelada pelo luckperms.

**Capturas de tela e registros**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Envie seus registros para https://gist.github.com/

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Thermos-1.7.10-1614-server.jar
 - Versão do plug-in: PixelVip-2.0.4-b47-Universal.jar (Baixada a mais recente do spigot)
 - Versão do Java: java 8

**Contexto adicional**
Eu sei que tem como evitar o cancelamento da task mudando a config do luckperms, só estou aqui deixando um aviso que vai ter esse problema por não executar a task em async,e que pode até gerar lag em servidor com muito player.

**Comment by FabioZumbi12** [comment]
Vlw pela dica, arrumado na ultima dev build (eu acho)
