### ISSUE TITLE
[BUG] Error on server start

### ISSUE THREAD

**Issue by Nety01** [FabioZumbi12/PixelVip#35]
**Describe the bug**
Hi, I'm getting this error on server start https://pastebin.com/00BhCEkg

**Server and plugins versions (please complete the following information):**
 - Server: PaperSpigot 1.13.x 1.13.2 Build 643, development
 - Plugin Version: PixelVip-3.0.0-b66-Universal.jar
 - Java Version: Java SE 8u112

**Comment by CrazyDev** [comment]
I have tha same problem.
https://pastebin.com/W3mhYm1S

**Comment by FabioZumbi12** [comment]
Fixed on latest build
