### ISSUE TITLE
[Suggestion] Queuing items notification for player

### ISSUE THREAD

**Issue by TheNety** [FabioZumbi12/PixelVip#37]
When items are given to a player on VIP purchase and the player has for example 2 missing free slots in his inventory, the items will be queued until he has a place in his inventory and will be notified "Missing 2 free slots in your inventory! Items queued..." and then when the queued items will be given to him he will be notified "You got all items!" or something like that.

So players don't lose any items.

**Comment by FabioZumbi12** [comment]
The items is given using other plugins commands, as pixelvip just run commands on activations. The this other plugin need to take care about this.
