### ISSUE TITLE
PixelVip slowing down the server(?)

### ISSUE THREAD

**Issue by TheJoshue** [FabioZumbi12/PixelVip#39]
**Describe the bug**
I don't know how to describe this bug, it's literally doing wrong something on the server (paperspigot 1.8.8 but it's also generating almost the same timings on paperspigot 1.12.2), and so you just need to look at the timings
https://timings.aikar.co/?id=1b7286367f8240dcbc95158d3b817889

**Server and plugins versions (please complete the following information):**
 - Server: Paperspigot 1.8.8
 - Plugin Version: PixelVip-2.0.4-b53-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
You is not loosing TPS, you have some other problems like not using aikar's java argumments, like this message says: 
![image](https://user-images.githubusercontent.com/5833818/82501387-90681400-9acb-11ea-8202-997ccf196700.png)
