### ISSUE TITLE
PagSeguro and Paypal support

### ISSUE THREAD

**Issue by evernife** [FabioZumbi12/PixelVip#4]
Toda a automação do pixelvip torna ele muito melhor do que o vipzero.

Contudo, não é possível automatizar 100% do trabalho sem ter um hook com o sistema de pagamento.
Seria interessante adicionar um método de ativação com o código de pagamento.

[Pagina do API do VipZero](https://dev.bukkit.org/projects/vipzero/pages/pag-seguro-pt-br)

**Comment by FabioZumbi12** [comment]
Por enquanto so pagseguro.
