### ISSUE TITLE
[BUG] Incializaçao com MySQL

### ISSUE THREAD

**Issue by guimartino** [FabioZumbi12/PixelVip#43]
Boa noite, tudo bem?? :) 

**Descrição**
Erro de inicialização do plugin ao mudar a configuração para utilizar MYSQL

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Iniciar o servidor com o plugin instalado
2. Fechar o servidor após criação do arquivo de configurações
3. Alterar para MySQL e preencher o campo de database, user e password
4. Iniciar o servidor

**Comportamento esperado**
Iniciar o plugin e criar as tabelas no MySQL

**Capturas de tela e registros**
![image](https://user-images.githubusercontent.com/3578494/80298140-b0701600-875f-11ea-8ebe-56577254f421.png)

Configurações
![image](https://user-images.githubusercontent.com/3578494/80298174-ead9b300-875f-11ea-83c6-976c89771462.png)

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: **Spigot 1.13.2**
 - Versão do plug-in: **PixelVip-3.0.0-b65-Universal.jar**
 - Versão do Java: **Java 1.8**

Desde ja agradeço, espero não estar fazendo nenhuma besteira na configuração hahahaha

**Comment by FabioZumbi12** [comment]
Arrumado na ultima versão
