### ISSUE TITLE
[BUG] Não é possivel desativar o VIP

### ISSUE THREAD

**Issue by DGabriel13** [FabioZumbi12/PixelVip#45]
**Descreva o bug**
Bem, quando você da /viptime 2 vezes ele não desativa o vip

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Digite /viptime'

**Comportamento esperado**
Pela Print era para desativar o vip quando digitar "/viptime" 2 vezes seguidas

**Capturas de tela e registros**
Meu Server:
![image](https://user-images.githubusercontent.com/58773688/80550517-b7cd3480-8996-11ea-87a2-c0e6ece16386.png)

Print do Plugin:
![image](https://user-images.githubusercontent.com/58773688/80550553-d2071280-8996-11ea-94a4-b0ac0eab843e.png)

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Server Version: git-Paper-1618 (MC: 1.12.2)
 - Versão do plug-in: PixelVIP 3.0.0
 - Versão do Java: [por exemplo Java 8]

**Comment by FabioZumbi12** [comment]
Não tem essa função de desativar. A print é das primeiras versões do plugn mas mesmo assim ela não diz isso, apenas esta em ingles.
