### ISSUE TITLE
[Impossibilidade de ativar o vip] 

### ISSUE THREAD

**Issue by michaelmatteus** [FabioZumbi12/PixelVip#46]
**Descreva o bug**

Ao executar o comando /usarkey [Código de Transação, neste caso o paypal] o membro não conseguiu ativar o vip e ao contrário deu o seguinte erro: https://pastebin.com/GQF8as0Y

EDIT (09/05/2020): fiz o teste usando as keys feitas in-game e deu no mesmo

Dentro do jogo simplesmente aparece a mensagem de aviso de inventário (tenha certeza de ter inventário suficiente bla bla bla) e após ele executar denovo, simplesmente acontece nada

**Comportamento esperado**
O vip deveria ser ativado

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Spigot 1.14.2
 - Versão do plug-in: PixelVip-3.0.0-b65-Universal.jar
 - Versão do Java: build 1.8.0_251-b08

**Comment by FabioZumbi12** [comment]
Testa denovo baixando o jar da sdk se da erro ainda: https://github.com/FabioZumbi12/PixelVip/tree/master/apis

**Comment by michaelmatteus** [comment]
Informo que o problema ja foi solucionado com as novas atualizações do plugin, obrigado!
