### ISSUE TITLE
[Suggestion] PlaceholderAPI placeholders in commands

### ISSUE THREAD

**Issue by TheNety** [FabioZumbi12/PixelVip#49]
**Is your feature request related to a problem? Please describe.**
I can't parse {p} to custom command made with MyCommand plugin.

**Describe the solution you'd like**
1. Solution: parse {p} placeholder for another plugins like MyCommand

2. Solution: Add PlaceholderAPI support for PixelVIP commands on vip activation etc. So I can use %player_name%, for example.

**Comment by FabioZumbi12** [comment]
The name need to be parsed in your/other plugins to picelvip works
