### ISSUE TITLE
PixelVip placeholderapi

### ISSUE THREAD

**Issue by linkinkov** [FabioZumbi12/PixelVip#5]
hello, i see, that you add placeholderapi support. How to use it?

**Comment by linkinkov** [comment]
@FabioZumbi12 please answer

**Comment by FabioZumbi12** [comment]
Sorry. You can use placeholderAPI to get some info about the player vip. The placeholders are:

`expiration_millis_{player}` - Give the remain player vip time in milliseconds
`expiration_desc_{player}` -  Give a the description with the reamin vip time of player
`active_vip_{player}` - Get the active Vip group the player is using

**Comment by linkinkov** [comment]
@FabioZumbi12 %active_vip_{player}% ?
{player} will be converted to player name?

**Comment by linkinkov** [comment]
I test it, but its just write active_vip_linkinkov

**Comment by FabioZumbi12** [comment]
Fixed on latest builds.
