### ISSUE TITLE
[LINKOFF] PixelVipBungeeBrige Link

### ISSUE THREAD

**Issue by zanatarp** [FabioZumbi12/PixelVip#50]
Boa noite,

O link do PixelVipBungeeBrige está quebrado, onde posso encontrar para download ?

**Comment by zanatarp** [comment]
A pagina onde o link esta off:
https://github.com/FabioZumbi12/PixelVip/wiki/(3)-BungeeCoord

**Comment by FabioZumbi12** [comment]
Fixed on wiki, thanks
