### ISSUE TITLE
Does this plug-in have variables？

### ISSUE THREAD

**Issue by nailao946** [FabioZumbi12/PixelVip#51]
i‘m on these contents on the https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders website：
PixelVip
NO DOWNLOAD COMMAND

%pixelvip_expiration_millis%
%pixelvip_expiration_desc%
%pixelvip_active_vip%

but it's not use when i add it

**Comment by FabioZumbi12** [comment]
Yeah, it works
