### ISSUE TITLE
[BUG] Vips não ativam - MP

### ISSUE THREAD

**Issue by Eumanuel** [FabioZumbi12/PixelVip#53]
**Descreva o bug**
Ele encontra o pacote, no entanto ocorre um erro ao adicionar o pacote no inventário do jogador.
Pacote: https://drive.google.com/uc?id=1F_JNVGYVvfnIXzQB6b1D8NSlMfdZEzTK
Configuração: https://drive.google.com/uc?id=1-IlNvXA8KNTbW7Q03sOu2E9PHnT6xVx0
Erro: https://drive.google.com/uc?id=1QuvHwtV5LHejlt3GXhd-7ry5zC8r-KjT

É claro que ele acessa corretamente o sistema do mercado pago, pois a string "Teste" está presente dentro do pacote no mercado pago, e não nas configurações do plugin em si.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Apenas crie um pacote e compre-o usando mercado pago

**Comportamento esperado**
O pacote ativar normalmente

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Paper 1.16.4 (Testado também no spigot 1.16.4)
 - Versão do plug-in: PixelVip-3.0.3-b82-Universal
 - Versão do Java: Java 11

**Comment by FabioZumbi12** [comment]
#59 :/
