### ISSUE TITLE
[BUG] Pagamento automático via PayPal

### ISSUE THREAD

**Issue by Focxer** [FabioZumbi12/PixelVip#59]
**Descreva o bug**
Quando alguem ativa a key (ID da transação), nada acontece mas aparece isto no console

`[22:46:11 INFO]: Give a package with optional variant to player.`
`[22:46:11 INFO]: /givepackage <player> <id>`

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Ter uma chave de compra em `transactions.yml`
2. Ter uma package com um comando de teste criada com o mesmo ID do produto adquirido
3. Ativar o código do VIP (ID da transação)
4. Veja nada acontecer

**Comportamento esperado**
No meu teste eu simulei o comando `/eco give {p} 1` sem o barra nas configs e nada acontece, exceto a mensagem no console:
`[22:46:11 INFO]: Give a package with optional variant to player.`
`[22:46:11 INFO]: /givepackage <player> <id>`
como se eu tivesse errado algo, placeholder/comando

**Capturas de tela e registros**
https://gist.github.com/Focxer/d4cd42da06078dd37329de6d14407caa

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: `Paper version git-Paper-75 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: cc063e1)`
 - Versão do plug-in: `PixelVip-3.0.3-b84-Universal.jar`
- Versão do Java: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9)

**Contexto adicional**
Não é problema na parte de detecção de pagamento e ID de transação da PayPalAPI.jar creio eu, pois o plugin exerce sua função corretamente, entretanto... ao tentar executar no jogo`/givepackage MeuNick 1` funciona perfeitamente. Qualquer informação sobre como eu possa corrigir isto, sou o Focxer que entrou em contato com você via Discord focxer#2857

**EDIT**
troquei ID por DESCRICAO e aparece isso no console agora, como se não estivesse uma package setada na config, aparentemente falta a substituição do ID da package no comando executado
```[14:41:51 INFO]: [PixelVip] ---------
[14:41:51 INFO]: [PixelVip] ID:
[14:41:51 INFO]: [PixelVip] Quantity: 1
[14:41:51 INFO]: [PixelVip] Title: VIP 30 Dias Either's Fell #1
[14:41:51 INFO]: [PixelVip] Price: 28.90
[14:41:51 INFO]: [PixelVip] ---------
[14:41:51 INFO]: [PixelVip] Added Item: VIP 30 Dias Either's Fell #1 | ID:
[14:41:51 INFO]: Give a package with optional variant to player.
[14:41:51 INFO]: /givepackage <player> <id>```

LOG:
```06.07.2021 - 14:41:51 - PixelVip Log: Running Command - "givepackage Focxer "
06.07.2021 - 14:41:51 - PixelVip Log: API:PayPal | Focxer | Item Cmd:givepackage Focxer  | Transaction Code: 65U67137NK627800P```

**Comment by Focxer** [comment]
```05.07.2021 - 22:54:30 - PixelVip Log: API:PayPal | Focxer | Item Cmd:givepackage Focxer  | Transaction Code: 65U67137NK627800P```

tem isso aqui no Log dele, ele não ta usando o ID das packages

**Comment by FabioZumbi12** [comment]
Infelizmente as apis não funcionam mais e estão desatualizadas :/
