### ISSUE TITLE
[BUG] Console Error

### ISSUE THREAD

**Issue by Epolision** [FabioZumbi12/PixelVip#62]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/PixelVip>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
It gives an error to the console and some users get the Vip tag even though they have Vip duration.

**To Reproduce**

**Expected behavior**
Not getting the VIP tag of the players and solving the error

**Screenshots and LOGs**
https://prnt.sc/1uh540l

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.8
 - Plugin Version:  PixelVip-3.0.3
 - Java Version:  Java 1.8

**Additional context**

We don't want the vips to be deleted, they open support and we have to fix it one by one, so our job gets harder.

**Comment by FabioZumbi12** [comment]
Should be fixed on latest dev builds http://host.areaz12server.net.br:8081/job/PixelVip/lastBuild/
