### ISSUE TITLE
[Suggestion] Additional PAPI placeholders

### ISSUE THREAD

**Issue by TheJoshue** [FabioZumbi12/PixelVip#63]
besides `%pixelvip_active_vip%`

Can you add:
`%pixelvip_vip_#%` where "#" is number

If we parse:
`%pixelvip_inactive_2%` for player "Grumm" that has 3 vips (1 active vip & 2 paused vips), the PAPI placeholder (`%pixelvip_inactive_2%`) will return the SECOND PAUSED VIP (because there is "2" in the placeholder).

If player has only 2 paused vips, the `%pixelvip_inactive_3%` will return nothing

Aswell as potentially add:
`%pixelvip_inactive_#_expiration_millis%`
`%pixelvip_inactive_#_expiration_desc%`

While keeping:
`%pixelvip_expiration_millis%`
`%pixelvip_expiration_desc%`
`*`And as before they will return values of the current active vip

**Comment by FabioZumbi12** [comment]
Added just a list of inactive vips
