### ISSUE TITLE
erro console

### ISSUE THREAD

**Issue by brasilcraft54** [FabioZumbi12/PixelVip#64]
console erro fica dando isso toda hora: https://pastebin.com/cN0P6kBD

paper 1.17.1

versão do plugin: PixelVip-3.0.3-b84-Universal.jar

isso acontece toda hora no console estou usando a ultima versão do Vault.

**Comment by FabioZumbi12** [comment]
É apenas um alerta do LuckPerms dizendo que um plugin esta solicitando informações de players offline. vc pode desabilitar essa mensagem na config do LuckPerms.
