### ISSUE TITLE
[Suggestion] PermissionsEX method.

### ISSUE THREAD

**Issue by NinoM4ster** [FabioZumbi12/PixelVip#7]
I'm sure this happened to a few people:
Using a RankUp system and having issues while trying to integrate it with PixelVIP.
(PixelVIP replaces the current PEX group with the VIP group, making the player lose the original group while the VIP is activated)

It is possible, but it's complicated for newbies and since it's a workaround, it may cause more issues.

So, my suggestion is to add an option in the config file to change the PEX group managing method,
so the owner can choose between SET and ADD methods, turning things a lot easier.

This will make the player have both groups (RankUp/Member **AND** the VIP) at the same time.
(having the prefix/suffix priority defined by [the "weight" option in PEX config](https://www.spigotmc.org/threads/tutorial-understanding-permissionsexs-weight-system.68459/))

Example:
if you define the "set" value in the config, PixelVIP will execute `/pex user {p} group set {group}`, as it usually does.
but if you put "add", it will execute  `/pex user {p} group add {group}`

Thanks for the attention.

**Comment by FabioZumbi12** [comment]
This is already allowed on configurations.
