### ISSUE TITLE
Encantamentos

### ISSUE THREAD

**Issue by ruidavide** [FabioZumbi12/PixelVip#8]
Como é que adiciono itens encantados (armas, armaduras etc) nos meus vips?

**Comment by FabioZumbi12** [comment]
Cria kits com seu plugin de kit e da esse kit pro player na ativação. O PixelVip vai executar qqr comando, de qqr tipo, então vc pode usar, por exemplo, o essentials pra dar itens encantados por comando (veja como fazer no essentials).
